services:
  - type: web
    name: backnest
    env: node
    region: frankfurt # or oregon / singapore (pick nearest)
    plan: free
    buildCommand: "npm install && npx run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: mono_commerce
          property: connectionString

databases:
  - name: setupnest
    plan: free
